spring:
  profiles:
    active: dev
---
spring.config.activate.on-profile: dev
# spring datasource
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/file-server
    username: sa
    password:
  # H2 설정
  h2:
    console:
      enabled: true
      path: /h2
  # jpa 설정
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    open-in-view: true
    show-sql: true
    #log.org.hibernate.SQL=debug
logging:
  level.org.hibernate.SQL: debug
